workflows:
  expo-build:
    name: Expo EAS Build (Signed IPA for iOS, APK for Android)
    environment:
      groups:
        - expo-env-vars
    scripts:
      - name: Install dependencies
        script: |
          echo "Setting up Node.js..."
          nvm install $NODE_VERSION
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build Expo project using EAS Build
        script: |
          eas build --platform ios --profile development --non-interactive
          eas build --platform android --profile development --non-interactive
    artifacts:
      - ./dist/*.ipa
      - ./dist/*.apk
